name: Deploy FastAPI to GCP VM
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: project-insomniacs
          
      - name: Copy files to GCP VM
        run: |
          INSTANCE_NAME=instance-20241103-080640
          VM_ZONE=us-central1-a
          LOCAL_USER=mashovi06
          APP_DIR=/home/$LOCAL_USER/app
          
          # First, create directory as the correct user
          gcloud compute ssh $LOCAL_USER@$INSTANCE_NAME --zone=$VM_ZONE --quiet \
            --command "mkdir -p $APP_DIR"
          
          # Copy files with correct user permissions
          gcloud compute scp --zone=$VM_ZONE --quiet \
            --recurse ./* $LOCAL_USER@$INSTANCE_NAME:$APP_DIR
          
      - name: Restart FastAPI Service
        run: |
          INSTANCE_NAME=instance-20241103-080640
          VM_ZONE=us-central1-a
          LOCAL_USER=mashovi06
          
          # Restart service (using sudo with the correct user)
          gcloud compute ssh $LOCAL_USER@$INSTANCE_NAME --zone=$VM_ZONE --quiet \
            --command "sudo systemctl restart fastapi"
