name: Deploy FastAPI to GCP VM
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup GCloud Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: project-insomniacs
          
      - name: Copy files to GCP VM
        run: |
          INSTANCE_NAME=instance-20241103-080640
          VM_ZONE=us-central1-a  # Replace with your VM's zone
          APP_DIR=/home/mashovi06/app
          
          # Create directory with instance name
          gcloud compute ssh $INSTANCE_NAME --zone=$VM_ZONE --command "mkdir -p $APP_DIR"
          
          # Copy files with instance name
          gcloud compute scp --zone=$VM_ZONE --recurse ./* $INSTANCE_NAME:$APP_DIR
          
      - name: Restart FastAPI Service
        run: |
          INSTANCE_NAME=instance-20241103-080640
          VM_ZONE=us-central1-a  # Replace with your VM's zone
          
          # Restart service with instance name
          gcloud compute ssh $INSTANCE_NAME --zone=$VM_ZONE --command "sudo systemctl restart fastapi"
