name: Deploy FastAPI to GCP VM

on:
  push:
    branches:
      - main  # Trigger on the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Match the Python version on your GCP VM

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate with Google Cloud
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-key.json
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > $GOOGLE_APPLICATION_CREDENTIALS
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud config set project project-insomniacs  # Replace with your project ID

      - name: Copy files to GCP VM
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-key.json
        run: |
          VM_IP=YOUR_GCP_VM_IP  # Replace with your VM IP
          VM_USER=YOUR_VM_USERNAME  # Replace with your VM username
          APP_DIR=/path/to/app  # Replace with the actual path on the VM

          gcloud compute ssh $VM_USER@$VM_IP --command "mkdir -p $APP_DIR"
          gcloud compute scp --recurse ./* $VM_USER@$VM_IP:$APP_DIR

      - name: Restart FastAPI Service
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-key.json
        run: |
          VM_IP=YOUR_GCP_VM_IP  # Replace with your VM IP
          VM_USER=YOUR_VM_USERNAME  # Replace with your VM username

          gcloud compute ssh $VM_USER@$VM_IP --command "sudo systemctl restart fastapi"  # Ensure service name is correct
