# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt

      - name: Run tests
        run: |
          # Here you can add your test command, e.g. pytest
          echo "No tests defined yet."

      - name: Upload code to GCP VM
        env:
          GOOGLE_SA_KEY: ${{ secrets.GOOGLE_SA_KEY }}  # Service Account Key in JSON format
        run: |
          echo "$GOOGLE_SA_KEY" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project your-project-id
          gcloud compute scp --recurse app/ your-vm-instance-name:~/app --zone your-vm-zone

      - name: SSH into GCP VM and run the FastAPI app
        env:
          GOOGLE_SA_KEY: ${{ secrets.GOOGLE_SA_KEY }}  # Service Account Key in JSON format
        run: |
          echo "$GOOGLE_SA_KEY" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud compute ssh your-vm-instance-name --zone your-vm-zone --command "
            cd ~/app && \
            pip install -r requirements.txt && \
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > fastapi.log 2>&1 &
          "
